project:
  type: website
  output-dir: _site

website:
  title: "DSAC Quarto Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.html
        text: Slides
      - href: demo_base.html
        text: Base Demo
      - href: demo_fancy.html
        text: Fancy Demo
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/DSACMS/dsac_quarto_demo
        aria-label: GitHub

format:
  html:
    #theme: cosmo 
    #css: dsac-theme.css 
    toc: true